### ISSUE TITLE
Treatment to `...` in tf_estimator signature

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfestimators#76]
@kevinushey I realized that you added `...` to `train(), predict(), evaluate()`'s signature. However, there are no additional arguments available in the Python interface. Should we get rid of them or is this on purpose, e.g. to facilitate the templated roxygen documentation that I should be aware of?

**Comment by kevinushey** [comment]
They're there mainly for compatibility with R's S3 dispatch.

The generic methods are defined as e.g.

    train <- function(object, ...) UseMethod("train")

And because of that, all methods implementing that generic need to have both `object` and `...` in their signature, e.g.

    train.tf_estimator <- function(object, <stuff>, ...) { ... }

That is, because the generic has both `object` and `...` in its signature, the implementing method needs to also accept `object` and `...`. (even if `...` is unused by the implementing method)

**Comment by terrytangyuan** [comment]
Got it. Thanks for the clarification!
